
#Electric Furnace Settings
["Electric Furnace"]
	#Maximum Power for the Electric Furnace to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Electric Furnace
	#Range: > 0
	"Power Consumption" = 64
	#Power I/O per tick for the Electric Furnace
	#Range: > 0
	"Maximum Transfer" = 1000

#Solar Panel
["Solar Panel"]
	#Value for power generation for the Solar Panel
	#Range: > 0
	"Generation Rate" = 128
	#Maximum Power for the Solar Panel to store
	#Range: > 0
	"Maximum Power" = 250000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Maximum power to send out per tick for the Solar Panel
	#Range: > 0
	"Maximum Transfer" = 5000

#Primitive Stirling Generator Settings
["Primitive Stirling Generator"]
	#Power generation per tick
	#Range: > 0
	"Generation (Per Tick)" = 40
	#Power generation to send per tick
	#Range: > 0
	"Output Rate" = 1000
	#Maximum power for the Primitive Stirling Generator to store
	#Range: > 0
	"Maximum Power" = 100000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1

#Distillation Unit Settings
["Distillation Unit"]
	#Maximum Power for the Distillation Unit to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Distillation Unit
	#Range: > 0
	"Power Consumption" = 64
	#Power I/O per tick for the Distillation Unit
	#Range: > 0
	"Maximum Transfer" = 2500

#World Generation Settings
["World Generation"]
	#Enable/Disable Voluminous Energy biomes
	"Enable VE Biomes" = true
	#Enable/Disable all Voluminous Energy changes to feature generation
	"World Generation" = true

	#Feature Generation
	["World Generation"."Feature Generation"]
		#Enable/Disable Logging of Word Generation information for Voluminous Energy features and Ores
		"Enable Logging" = true
		#Enable/Disable Oil Lakes
		"Oil Lakes" = true
		#Oil Geyser Chance (Lower = Higher chance)
		#Range: > 10
		"Oil Geyser Chance" = 208
		#Underground Oil Lake Chance (Lower = Higher chance)
		#Range: > 10
		"Underground Oil Lake Chance" = 16
		#Enable/Disable Oil Geysers
		"Oil Geysers" = true
		#Enable/Disable Generation of Rice Crop
		"Generate Rice" = true
		#Rice Chance (Lower = Higher chance)
		#Range: > 10
		"Rice Chance" = 32
		#Enable/Disable Generation of Rice Crop in Oceans
		"Generate Rice in Oceans" = false
		#Surface Oil Lake Chance (Lower = Higher chance)
		#Range: > 10
		"Surface Oil Lake Chance" = 144

	#Ore Generation
	["World Generation"."Ore Generation"]

		#Cinnabar Ore Settings
		["World Generation"."Ore Generation"."Cinnabar Ore Settings"]
			#Range: > 0
			"Cinnabar Size" = 6
			#Enable/Disable generation of Cinnabar Ore
			"Enable Cinnabar Ore" = true
			#NOTE: Deprecated. Use a datapack to change the tag.
			#Range: > 0
			"Harvest Level" = 2
			#Range: 0 ~ 256
			"Cinnabar Top Anchor" = 256
			#Range: > 1
			"Cinnabar Weight" = 9
			#Range: 1 ~ 256
			"Cinnabar Bottom Anchor" = 1

		#Eighzo Ore Settings
		["World Generation"."Ore Generation"."Eighzo Ore Settings"]
			#Range: 0 ~ 256
			"Eighzo Top Anchor" = 36
			#Range: 1 ~ 256
			"Eighzo Bottom Anchor" = 1
			#NOTE: Deprecated. Use a datapack to change the tag.
			#Range: > 0
			"Harvest Level" = 5
			#Enable/Disable generation of Eighzo Ore
			"Enable Eighzo Ore" = true
			#Range: > 0
			"Eighzo Size" = 4
			#Range: > 1
			"Eighzo Weight" = 1

		#Saltpeter Ore Settings
		["World Generation"."Ore Generation"."Saltpeter Ore Settings"]
			#Range: 0 ~ 256
			"Saltpeter Top Anchor" = 256
			#NOTE: Deprecated. Use a datapack to change the tag.
			#Range: > 0
			"Harvest Level" = 0
			#Enable/Disable generation of Saltpeter Ore
			"Enable Saltpeter Ore" = true
			#Range: > 1
			"Saltpeter Weight" = 4
			#Range: > 0
			"Saltpeter Size" = 33
			#Range: 1 ~ 256
			"Saltpeter Bottom Anchor" = 55

		#Galena Ore Settings
		["World Generation"."Ore Generation"."Galena Ore Settings"]
			#Range: > 1
			"Galena Weight" = 3
			#NOTE: Deprecated. Use a datapack to change the tag.
			#Range: > 0
			"Harvest Level" = 2
			#Enable/Disable generation of Galena Ore
			"Enable Galena Ore" = true
			#Range: 0 ~ 256
			"Galena Top Anchor" = 32
			#Range: 0 ~ 16
			"Galena Light Glow Level" = 4
			#Range: 1 ~ 256
			"Galena Bottom Anchor" = 12
			#Range: > 0
			"Galena Size" = 6

		#Rutile Ore Settings
		["World Generation"."Ore Generation"."Rutile Ore Settings"]
			#Enable/Disable generation of Rutile Ore
			"Enable Rutile Ore" = true
			#NOTE: Deprecated. Use a datapack to change the tag.
			#Range: > 0
			"Harvest Level" = 3
			#Range: > 0
			"Rutile Size" = 4
			#Range: 1 ~ 256
			"Rutile Bottom Anchor" = 1
			#Range: > 1
			"Rutile Weight" = 3
			#Range: 0 ~ 256
			"Rutile Top Anchor" = 16

		#Bauxite Ore Settings
		["World Generation"."Ore Generation"."Bauxite Ore Settings"]
			#Range: 1 ~ 256
			"Bauxite Bottom Anchor" = 10
			#Range: 0 ~ 256
			"Bauxite Top Anchor" = 60
			#Range: > 0
			"Bauxite Size" = 8
			#NOTE: Deprecated. Use a datapack to change the tag.
			#Range: > 0
			"Harvest Level" = 1
			#Enable/Disable generation of Bauxite Ore
			"Enable Bauxite Ore" = true
			#Range: > 1
			"Bauxite Weight" = 16

#Stirling Generator Settings
["Stirling Generator"]
	#Maximum Power for the Stirling Generator to store
	#Range: > 0
	"Maximum Power" = 5120000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Fallback value for power generation for the Stirling Generator
	#Range: > 0
	"Fallback Generation Rate" = 128
	#Maximum power to send out per tick for the Stirling Generator
	#Range: > 0
	"Maximum Transfer" = 128000

#Centrifugal Agitator Settings
["Centrifugal Agitator"]
	#Maximum Power for the Centrifugal Agitator to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Centrifugal Agitator
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Centrifugal Agitator
	#Range: > 0
	"Maximum Transfer" = 1000

#Compressor Settings
[Compressor]
	#Maximum Power for the Compressor to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Compressor
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Compressor
	#Range: > 0
	"Maximum Transfer" = 1000

#Centrifugal Separator
["Centrifugal Separator"]
	#Maximum Power for the Centrifugal Separator to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Centrifugal Separator
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Centrifugal Separator
	#Range: > 0
	"Maximum Transfer" = 1000

#Gas Furnace Settings
["Gas Furnace"]
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1

#Primitive Solar Panel
["Primitive Solar Panel"]
	#Value for power generation for the Primitive Solar Panel
	#Range: > 0
	"Generation Rate" = 64
	#Maximum Power for the Primitive Solar Panel to store
	#Range: > 0
	"Maximum Power" = 100000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Maximum power to send out per tick for the Primitive Solar Panel
	#Range: > 0
	"Maximum Transfer" = 1000

#Blast Furnace
["Blast Furnace"]
	#Amount of fluid that is consumed per blasting operation for heat
	#Range: 0 ~ 4000
	"Heat Source Consumption" = 50
	#Maximum Power for the Blast Furnace to store
	#Range: > 0
	"Maximum Power" = 512000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 3
	#Power consumption per tick for the Blast Furnace
	#Range: > 0
	"Power Consumption" = 256
	#Power I/O per tick for the Blast Furnace
	#Range: > 0
	"Maximum Transfer" = 10000

#Pump Settings
[Pump]
	#Maximum Power for the Pump to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Pump
	#Range: > 0
	"Power Consumption" = 16
	#Power I/O per tick for the Pump
	#Range: > 0
	"Maximum Transfer" = 1000

#Aqueoulizer Settings
[Aqueoulizer]
	#Maximum Power for the Aqueoulizer to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Aqueoulizer
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Aqueoulizer
	#Range: > 0
	"Maximum Transfer" = 1000

#Battery Box Settings
["Battery Box"]
	#Maximum Power for the Battery Box to store
	#Range: > 0
	"Maximum Power" = 50000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power I/O per tick for the Battery Box
	#Range: > 0
	"Maximum Transfer" = 5000

#Air Compressor Settings
["Air Compressor"]
	#Maximum Power for the Air Compressor to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Air Compressor
	#Range: > 0
	"Power Consumption" = 24
	#Power I/O per tick for the Air Compressor
	#Range: > 0
	"Maximum Transfer" = 1000

#Crusher Settings
[Crusher]
	#Maximum power for the Crusher to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Crusher
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Crusher
	#Range: > 0
	"Maximum Transfer" = 1000

#Combustion Generator Settings
["Combustion Generator"]
	#Maximum Power for the Combustion Generator to store
	#Range: > 0
	"Maximum Power" = 5120000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#The fixed process time for the Combustion Generator is Balanced Mode is not used.
	#Range: > 0
	"Fixed Process Time" = 1600
	#Maximum power to send out per tick for the Combustion Generator
	#Range: > 0
	"Maximum Transfer" = 512000
	#If true, the Combustion Generator will use the process time from the oxidizer's recipe rather than the static process time
	"Balanced Mode" = false

#General Settings
[General]
	#Allow pipes to extract fluids from fluid input tanks. Disabling this means that only fluid outputs can be extracted from Tile Entites
	"Allow Extraction from Input Tanks" = false
	#How many uses a Solarium tool can have before the protective sheath is depleted
	#Range: > 0
	"Solarium Protective Sheath" = 2560
	#Duration of fire on an entity for stepping into an acid.
	#Range: > 0
	"Acid Fire Duration" = 4
	#Damage taken from standing in an acid.
	#Range: 0.0 ~ 3.4028234663852886E38
	"Acid Damage" = 3.0

#Implosion Compressor
["Implosion Compressor"]
	#Maximum Power for the Implosion Compressor to store
	#Range: > 0
	"Maximum Power" = 128000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 2
	#Power consumption per tick for the Implosion Compressor
	#Range: > 0
	"Power Consumption" = 128
	#Power I/O per tick for the Implosion Compressor
	#Range: > 0
	"Maximum Transfer" = 2500

#Electrolyzer Settings
[Electrolyzer]
	#Maximum Power for the Electrolyzer to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Electrolyzer
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Electrolyzer
	#Range: > 0
	"Maximum Transfer" = 1000

#Food Settings
[Food]
	#Nutritional value of Cooked Rice.
	#Range: > 1
	"Cooked Rice Nutrition" = 5
	#Chance of Rice crop going to next life stage.
	#Range: 1.1754943508222875E-38 ~ 1.0
	"Rice Tick Chance" = 0.5
	#Saturation of Cooked Rice.
	#Range: 1.1754943508222875E-38 ~ 3.4028234663852886E38
	"Cooked Rice Saturation" = 0.30000001192092896

